### ISSUE TITLE
UMAT is Fortran, how do we enable testing in multiple platforms

### ISSUE THREAD

**Issue by TeroFrondelius** [JuliaFEM/UMAT.jl#2]
I can try to use BinaryBuilder.jl to create cross-compiled example model library. @IvanYashchuk do you have suitable UMAT for testing?

**Comment by IvanYashchuk** [comment]
UMAT can be generated with MFront
http://tfel.sourceforge.net/abaqus.html

**Comment by TeroFrondelius** [comment]
I found one good test model: 
https://raw.githubusercontent.com/KratosMultiphysics/Kratos/master/applications/constitutive_laws_application/custom_external_libraries/umat/mises_umat.f
https://raw.githubusercontent.com/KratosMultiphysics/Kratos/master/applications/constitutive_laws_application/custom_external_libraries/umat/ABA_PARAM.INC

**Comment by TeroFrondelius** [comment]
https://github.com/TeroFrondelius/umat_binaries_builder

**Comment by TeroFrondelius** [comment]
These could be good test models: https://sourceforge.net/p/parafem/code/HEAD/tree/trunk/parafem/src/umats/dp/

**Comment by TeroFrondelius** [comment]
Done in #3
